// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "IIOP::BiDirIIOPServiceContext", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IiopBiDirIIOPServiceContext struct {
	__goidl__.IdlObject
	ListenPoints IiopListenPointList `json:"ListenPoints"`
}

//noinspection GoSnakeCaseUsage
const IiopBiDirIIOPServiceContextId_Const = "IDL:omg.org/IIOP/BiDirIIOPServiceContext:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIiopBiDirIIOPServiceContext() *IiopBiDirIIOPServiceContext {
	//noinspection GoRedundantConversion
	return &IiopBiDirIIOPServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IiopBiDirIIOPServiceContextId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "listen_points", Type: "IIOP::ListenPointList" Scope: "IdlStruct"
		ListenPoints: IiopListenPointList{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IIOP::ListenPoint" Scope: "IdlStruct"
		Array: IiopListenPoint{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "host", Type: "IdlString" Scope: "StringType"
		Host: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "port", Type: "IdlUnsignedShort" Scope: "UnsignedShortType"
		Port: 0,
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIiopBiDirIIOPServiceContext(
	//"StructDclAllParamsConstructorParamService"
	ListenPoints IiopListenPointList) *IiopBiDirIIOPServiceContext {
	//noinspection GoRedundantConversion
	return &IiopBiDirIIOPServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IiopBiDirIIOPServiceContextId_Const,
		},
		ListenPoints: ListenPoints,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIiopBiDirIIOPServiceContext(randomGenerator __goidl__.IRandomDataGenerator) *IiopBiDirIIOPServiceContext {
	//noinspection GoRedundantConversion
	return &IiopBiDirIIOPServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IiopBiDirIIOPServiceContextId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "listen_points", Type: "IIOP::ListenPointList" Scope: "IdlStruct"
		ListenPoints: IiopListenPointList{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IIOP::ListenPoint" Scope: "IdlStruct"
		Array: IiopListenPoint{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "host", Type: "IdlString" Scope: "StringType"
		Host: randomGenerator.StringTypeValue(__reflect__.TypeOf((*IiopBiDirIIOPServiceContext)(nil)), "Host"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "port", Type: "IdlUnsignedShort" Scope: "UnsignedShortType"
		Port: randomGenerator.UnsignedShortTypeValue(__reflect__.TypeOf((*IiopBiDirIIOPServiceContext)(nil)), "Port"),
	},
	},
	}
}

func (self *IiopBiDirIIOPServiceContext) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopBiDirIIOPServiceContext) GoString() string {
	return self.String()
}

func (self *IiopBiDirIIOPServiceContext) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ListenPoints.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopBiDirIIOPServiceContext) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopBiDirIIOPServiceContext) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ListenPoints.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopBiDirIIOPServiceContext_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopBiDirIIOPServiceContextHelper = IiopBiDirIIOPServiceContext_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopBiDirIIOPServiceContextId_Const,
			__yaccidl__.IdlStruct,
			"IIOP.idl.BiDirIIOPServiceContext.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIiopBiDirIIOPServiceContext()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIiopBiDirIIOPServiceContext(generator)
			},
			__reflect__.TypeOf((*IiopBiDirIIOPServiceContext)(nil))))
}
