// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "IIOP::ListenPointList", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IiopListenPointList struct {
	__goidl__.IdlObject
	Array IiopListenPoint `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IiopListenPointListId_Const = "IDL:IIOP/ListenPointList:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIiopListenPointList() *IiopListenPointList {
	//noinspection GoRedundantConversion
	return &IiopListenPointList{
		IdlObject: __goidl__.IdlObject{
			Id: IiopListenPointListId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IIOP::ListenPoint" Scope: "IdlStruct"
		Array: IiopListenPoint{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "host", Type: "IdlString" Scope: "StringType"
		Host: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "port", Type: "IdlUnsignedShort" Scope: "UnsignedShortType"
		Port: 0,
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIiopListenPointList(
	//"StructDclAllParamsConstructorParamService"
	Array IiopListenPoint) *IiopListenPointList {
	//noinspection GoRedundantConversion
	return &IiopListenPointList{
		IdlObject: __goidl__.IdlObject{
			Id: IiopListenPointListId_Const,
		},
		Array: Array,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIiopListenPointList(randomGenerator __goidl__.IRandomDataGenerator) *IiopListenPointList {
	//noinspection GoRedundantConversion
	return &IiopListenPointList{
		IdlObject: __goidl__.IdlObject{
			Id: IiopListenPointListId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IIOP::ListenPoint" Scope: "IdlStruct"
		Array: IiopListenPoint{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "host", Type: "IdlString" Scope: "StringType"
		Host: randomGenerator.StringTypeValue(__reflect__.TypeOf((*IiopListenPointList)(nil)), "Host"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "port", Type: "IdlUnsignedShort" Scope: "UnsignedShortType"
		Port: randomGenerator.UnsignedShortTypeValue(__reflect__.TypeOf((*IiopListenPointList)(nil)), "Port"),
	},
	}
}

func (self *IiopListenPointList) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopListenPointList) GoString() string {
	return self.String()
}

func (self *IiopListenPointList) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Array.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopListenPointList) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopListenPointList) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopListenPointList_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopListenPointListHelper = IiopListenPointList_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopListenPointListId_Const,
			__yaccidl__.IdlStruct,
			"IIOP.idl.ListenPointList.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIiopListenPointList()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIiopListenPointList(generator)
			},
			__reflect__.TypeOf((*IiopListenPointList)(nil))))
}
