// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "IIOP::Version", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IiopVersion struct {
	__goidl__.IdlObject
	Major byte `json:"Major"`
	Minor byte `json:"Minor"`
}

//noinspection GoSnakeCaseUsage
const IiopVersionId_Const = "IDL:omg.org/IIOP/Version:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIiopVersion() *IiopVersion {
	//noinspection GoRedundantConversion
	return &IiopVersion{
		IdlObject: __goidl__.IdlObject{
			Id: IiopVersionId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major", Type: "IdlOctet" Scope: "IdlOctetKind"
		Major: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor", Type: "IdlOctet" Scope: "IdlOctetKind"
		Minor: 0,
	}
}

//noinspection GoUnusedExportedFunction
func NewIiopVersion(
	//"StructDclAllParamsConstructorParamService"
	Major byte,
	//"StructDclAllParamsConstructorParamService"
	Minor byte) *IiopVersion {
	//noinspection GoRedundantConversion
	return &IiopVersion{
		IdlObject: __goidl__.IdlObject{
			Id: IiopVersionId_Const,
		},
		Major: Major,
		Minor: Minor,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIiopVersion(randomGenerator __goidl__.IRandomDataGenerator) *IiopVersion {
	//noinspection GoRedundantConversion
	return &IiopVersion{
		IdlObject: __goidl__.IdlObject{
			Id: IiopVersionId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major", Type: "IdlOctet" Scope: "IdlOctetKind"
		Major: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IiopVersion)(nil)), "Major"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor", Type: "IdlOctet" Scope: "IdlOctetKind"
		Minor: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IiopVersion)(nil)), "Minor"),
	}
}

func (self *IiopVersion) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopVersion) GoString() string {
	return self.String()
}

func (self *IiopVersion) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.Major, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.Minor, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopVersion) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopVersion) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.Major)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.Minor)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopVersion_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopVersionHelper = IiopVersion_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopVersionId_Const,
			__yaccidl__.IdlStruct,
			"IIOP.idl.Version.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIiopVersion()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIiopVersion(generator)
			},
			__reflect__.TypeOf((*IiopVersion)(nil))))
}
