// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IIOP::ListenPointList", generatedBy by: "WriteStructSequenceDcl"
type IiopListenPointList struct {
	__goidl__.IdlObject
	Array []*IiopListenPoint `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IiopListenPointListId_Const = "IDL:IIOP/ListenPointList:1.0"

func (self *IiopListenPointList) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopListenPointList) GoString() string {
	return self.String()
}

func (self *IiopListenPointList) ReadValue(stream __goidl__.IReadAny) error {
	err := self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	var n uint32
	n, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	if n > 0 {
		self.Array = make([]*IiopListenPoint, n)
		var i uint32
		for i = 0; i < n; i++ {
			self.Array[i] = &IiopListenPoint{}
			err = self.Array[i].ReadValue(stream)
				if err != nil {
				return err
			}
		}
	}
	return nil
}

func (self *IiopListenPointList) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopListenPointList) Write(stream __goidl__.IWriteAny) error {
	err := self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	err = __goidl__.IdlUInt32Helper.Write(stream, uint32(len(self.Array)))
	if err != nil {
	return err
	}
	if len(self.Array) > 0 {
		for _, item := range self.Array {
			err = item.Write(stream)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopListenPointList_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopListenPointListHelper = IiopListenPointList_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopListenPointListId_Const,
			__goidl__.SequenceType,
			"IIOP.idl",
			"xdl_IiopListenPointList.go",
			func() __goidl__.IIdlObject {
				return &IiopListenPointList{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IiopListenPointList{}
			},
			__reflect__.TypeOf((*IiopListenPointList)(nil))))
}
