// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IIOP::BiDirIIOPServiceContext", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IiopBiDirIIOPServiceContext struct {
	__goidl__.IdlObject
	ListenPoints IiopListenPointList `json:"ListenPoints"`
}

//noinspection GoSnakeCaseUsage
const IiopBiDirIIOPServiceContextId_Const = "IDL:omg.org/IIOP/BiDirIIOPServiceContext:1.0"

func (self *IiopBiDirIIOPServiceContext) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopBiDirIIOPServiceContext) GoString() string {
	return self.String()
}

func (self *IiopBiDirIIOPServiceContext) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ListenPoints.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopBiDirIIOPServiceContext) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopBiDirIIOPServiceContext) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ListenPoints.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopBiDirIIOPServiceContext_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopBiDirIIOPServiceContextHelper = IiopBiDirIIOPServiceContext_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopBiDirIIOPServiceContextId_Const,
			__goidl__.StructType,
			"IIOP.idl",
			"xdl_IiopBiDirIIOPServiceContext.go",
			func() __goidl__.IIdlObject {
				return &IiopBiDirIIOPServiceContext{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IiopBiDirIIOPServiceContext{}
			},
			__reflect__.TypeOf((*IiopBiDirIIOPServiceContext)(nil))))
}
