// Code generated by me. DO NOT EDIT.

package goIdlIiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IIOP::ListenPoint", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IiopListenPoint struct {
	__goidl__.IdlObject
	Host string `json:"Host"`
	Port uint16 `json:"Port"`
}

//noinspection GoSnakeCaseUsage
const IiopListenPointId_Const = "IDL:omg.org/IIOP/ListenPoint:1.0"

func (self *IiopListenPoint) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IiopListenPoint) GoString() string {
	return self.String()
}

func (self *IiopListenPoint) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Host, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedShortType)
	self.Port, err = __goidl__.IdlUInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopListenPoint) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IiopListenPoint) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Host)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedShortType)
	err = __goidl__.IdlUInt16Helper.Write(stream, self.Port)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IiopListenPoint_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IiopListenPointHelper = IiopListenPoint_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IiopListenPointId_Const,
			__goidl__.StructType,
			"IIOP.idl",
			"xdl_IiopListenPoint.go",
			func() __goidl__.IIdlObject {
				return &IiopListenPoint{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IiopListenPoint{}
			},
			__reflect__.TypeOf((*IiopListenPoint)(nil))))
}
